
export const curatedHomepageSearchTerms: string[] = [
  'macbook pro',
  'macbook air',
  'iphone 14',
  'iphone 13',
  'iphone',
  'ipad pro',
  'ipad air',
  'ipad',
  'apple watch',
  'airpods pro',
  'gaming laptop',
  'playstation 5',
  'PS5 Console',
  'Ps4',
  'PS4 Console',
  'xbox series x',
  'xbox',
  'Elden Ring',
  'Ghost of Tsushima',
  'Roomba',
  'robot vacuum',
  'air fryer',
  'monitor',
  'TV',
  'nintendo switch',
  'No Man\'s Sky',
  'The Last of Us',
  'PS Portable',
  'Steam Deck',
  'laptop',
  'headphones',
  'smartwatch',
  'camera',
  'gaming console',
  'kitchen appliance',
  'tablet',
  'drone'
];
